apiVersion: devops.mysdktest.io/v1alpha1
kind: PingPongServer
metadata:
  labels:
    app.kubernetes.io/name: pingpongserver
    app.kubernetes.io/instance: pingpongserver-sample
    app.kubernetes.io/part-of: operator-sdk-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-sdk-project
  name: pingpongserver-sample
spec:
  # TODO(user): Add fields here
