# permissions for end users to view myhttpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myhttpserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-httpserver-operator
    app.kubernetes.io/part-of: my-httpserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: myhttpserver-viewer-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - myhttpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - myhttpservers/status
  verbs:
  - get
