apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-test-server
  template:
    metadata:
      labels:
        app: go-test-server
    spec:
      containers:
      - name: go-test-server
        image: brianleay/test-ping-pong:test-tag
        ports:
        - containerPort: 8083 # Change the container port to 8084
---
apiVersion: v1
kind: Service
metadata:
  name: go-test-server
spec:
  selector:
    app: go-test-server
  ports:
    - protocol: TCP
      port: 8084 # Change the port to 8084
      targetPort: 8084 # Change the target port to 8084
  type: LoadBalancer
