apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: http-servers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                interval:
                  type: string
                peers:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      port:
                        type: integer
  scope: Namespaced
  names:
    plural: http-servers
    singular: http-server
    kind: HTTPServer
    shortNames:
      - hs
